export const academicYearOptions = [
  { label: "select", value: "" },
  { label: "2019/2020", value: "2019/2020" },
  { label: "2020/2021", value: "2020/2021" },
  { label: "2021/2022", value: "2021/2022" },
  { label: "2022/2023", value: "2022/2023" },
  { label: "2023/2024", value: "2023/2024" },
  { label: "2024/2025", value: "2024/2025" },
  { label: "2025/2026", value: "2025/2026" },
  { label: "2026/2027", value: "2026/2027" },
  { label: "2027/2028", value: "2027/2028" },
];

export const level = [
  { label: "Select", value: "0" },
  { label: "Level 200", value: "200" },
  { label: "Level 300", value: "300" },
  { label: "Level 400", value: "400" },
  { label: "Level 500", value: "500" },
  { label: "Master 1", value: "600" },
  { label: "Master 2", value: "700" },
];

export const faculty = [
  { label: "Select", value: "0" },
  { label: "FET", value: "fet" },
  { label: "ASTII", value: "astii" },
  { label: "COT", value: "cot" },
  { label: "Agriculture", value: "ag" },
];
export const department = [
  { label: "Select", value: "0" },
  { label: "Computer eng", value: "comp" },
  { label: "Electrical", value: "elec" },
  { label: "Mechanical", value: "mecha" },
  { label: "civil eng", value: "civil" },
];

export const courses = [
  { label: "Select", value: "0" },
  { label: "Cloud computing and SOA", value: "CEF450" },
  { label: "FeedBack system Lab", value: "EEF460" },
  { label: "XML and doc. Cont.", value: "CEF482" },
  { label: "Software Verification and Validation techniques", value: "CEF474" },
  { label: "Advanced database and admin (Oracle ans MySQL)", value: "CEF438" },
  { label: "Human computer interface", value: "CEF472" },
  { label: "Internet Programing and Network", value: "CEF440" },
  { label: "Digital image processing", value: "CEF462" },
  { label: "Software Engineering and Design", value: "CEF476" },
  { label: "AI and Machine Learning", value: "CEF444" },
];

export const demoPersons = [
  {
    id: 1,
    matricule: "FE24A001",
    email: "person1@example.com",
    name: "John Doe",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/1/800/600",
  },
  {
    id: 2,
    matricule: "FE24A002",
    email: "person2@example.com",
    name: "Jane Smith",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/2/800/600",
  },
  {
    id: 3,
    matricule: "FE24A003",
    email: "person3@example.com",
    name: "Bob Johnson",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/3/800/600",
  },
  {
    id: 4,
    matricule: "FE24A004",
    email: "person4@example.com",
    name: "Sarah Lee",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/4/800/600",
  },
  {
    id: 5,
    matricule: "FE24A005",
    email: "person5@example.com",
    name: "Tom Williams",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/5/800/600",
  },
  {
    id: 6,
    matricule: "FE24A006",
    email: "person6@example.com",
    name: "Emily Davis",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/6/800/600",
  },
  {
    id: 7,
    matricule: "FE24A007",
    email: "person7@example.com",
    name: "Michael Brown",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/7/800/600",
  },
  {
    id: 8,
    matricule: "FE24A008",
    email: "person8@example.com",
    name: "Jessica Wilson",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/8/800/600",
  },
  {
    id: 9,
    matricule: "FE24A009",
    email: "person9@example.com",
    name: "David Anderson",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/9/800/600",
  },
  {
    id: 10,
    matricule: "FE24A010",
    email: "person10@example.com",
    name: "Olivia Thompson",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/10/800/600",
  },
  {
    id: 11,
    matricule: "FE24A011",
    email: "person11@example.com",
    name: "William Martinez",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/11/800/600",
  },
  {
    id: 12,
    matricule: "FE24A012",
    email: "person12@example.com",
    name: "Sophia Hernandez",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/12/800/600",
  },
  {
    id: 13,
    matricule: "FE24A013",
    email: "person13@example.com",
    name: "Daniel Flores",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/13/800/600",
  },
  {
    id: 14,
    matricule: "FE24A014",
    email: "person14@example.com",
    name: "Isabella Jimenez",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/14/800/600",
  },
  {
    id: 15,
    matricule: "FE24A015",
    email: "person15@example.com",
    name: "Christopher Reyes",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/15/800/600",
  },
  {
    id: 16,
    matricule: "FE24A016",
    email: "person16@example.com",
    name: "Avery Morales",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/16/800/600",
  },
  {
    id: 17,
    matricule: "FE24A017",
    email: "person17@example.com",
    name: "Lucas Fernandez",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/17/800/600",
  },
  {
    id: 18,
    matricule: "FE24A018",
    email: "person18@example.com",
    name: "Isabela Diaz",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/18/800/600",
  },
  {
    id: 19,
    matricule: "FE24A019",
    email: "person19@example.com",
    name: "Sebastian Ramirez",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/19/800/600",
  },
  {
    id: 20,
    matricule: "FE24A020",
    email: "person20@example.com",
    name: "Camila Vargas",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/20/800/600",
  },
  {
    id: 21,
    matricule: "FE24A021",
    email: "person21@example.com",
    name: "Mateo Gomez",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/21/800/600",
  },
  {
    id: 22,
    matricule: "FE24A022",
    email: "person22@example.com",
    name: "Emma Castillo",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/22/800/600",
  },
  {
    id: 23,
    matricule: "FE24A023",
    email: "person23@example.com",
    name: "Alejandro Torres",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/23/800/600",
  },
  {
    id: 24,
    matricule: "FE24A024",
    email: "person24@example.com",
    name: "Gabriela Sanchez",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/24/800/600",
  },
  {
    id: 25,
    matricule: "FE24A025",
    email: "person25@example.com",
    name: "Diego Perez",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/25/800/600",
  },
  {
    id: 26,
    matricule: "FE24A026",
    email: "person26@example.com",
    name: "Valentina Ortiz",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/26/800/600",
  },
  {
    id: 27,
    matricule: "FE24A027",
    email: "person27@example.com",
    name: "Javier Mora",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/27/800/600",
  },
  {
    id: 28,
    matricule: "FE24A028",
    email: "person28@example.com",
    name: "Emilia Rojas",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/28/800/600",
  },
  {
    id: 29,
    matricule: "FE24A029",
    email: "person29@example.com",
    name: "Mariano Rios",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/29/800/600",
  },
  {
    id: 30,
    matricule: "FE24A030",
    email: "person30@example.com",
    name: "Lucia Mendoza",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/30/800/600",
  },
  {
    id: 31,
    matricule: "FE24A031",
    email: "person31@example.com",
    name: "Andres Fuentes",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/31/800/600",
  },
  {
    id: 32,
    matricule: "FE24A032",
    email: "person32@example.com",
    name: "Martina Vega",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/32/800/600",
  },
  {
    id: 33,
    matricule: "FE24A033",
    email: "person33@example.com",
    name: "Pablo Soto",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/33/800/600",
  },
  {
    id: 34,
    matricule: "FE24A034",
    email: "person34@example.com",
    name: "Catalina Reyes",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/34/800/600",
  },
  {
    id: 35,
    matricule: "FE24A035",
    email: "person35@example.com",
    name: "Ignacio Moreno",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/35/800/600",
  },
  {
    id: 36,
    matricule: "FE24A036",
    email: "person36@example.com",
    name: "Valentina Flores",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/36/800/600",
  },
  {
    id: 37,
    matricule: "FE24A037",
    email: "person37@example.com",
    name: "Daniel Jimenez",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/37/800/600",
  },
  {
    id: 38,
    matricule: "FE24A038",
    email: "person38@example.com",
    name: "Isabella Ramirez",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/38/800/600",
  },
  {
    id: 39,
    matricule: "FE24A039",
    email: "person39@example.com",
    name: "Sebastian Morales",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/39/800/600",
  },
  {
    id: 40,
    matricule: "FE24A040",
    email: "person40@example.com",
    name: "Camila Fernandez",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/40/800/600",
  },
  {
    id: 41,
    matricule: "FE24A041",
    email: "person41@example.com",
    name: "Mateo Diaz",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/41/800/600",
  },
  {
    id: 42,
    matricule: "FE24A042",
    email: "person42@example.com",
    name: "Emma Vargas",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/42/800/600",
  },
  {
    id: 43,
    matricule: "FE24A043",
    email: "person43@example.com",
    name: "Alejandro Castillo",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/43/800/600",
  },
  {
    id: 44,
    matricule: "FE24A044",
    email: "person44@example.com",
    name: "Gabriela Torres",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/44/800/600",
  },
  {
    id: 45,
    matricule: "FE24A045",
    email: "person45@example.com",
    name: "Diego Sanchez",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/45/800/600",
  },
  {
    id: 46,
    matricule: "FE24A046",
    email: "person46@example.com",
    name: "Valentina Perez",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/46/800/600",
  },
  {
    id: 47,
    matricule: "FE24A047",
    email: "person47@example.com",
    name: "Javier Ortiz",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/47/800/600",
  },
  {
    id: 48,
    matricule: "FE24A048",
    email: "person48@example.com",
    name: "Emilia Mora",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/48/800/600",
  },
  {
    id: 49,
    matricule: "FE24A049",
    email: "person49@example.com",
    name: "Mariano Rios",
    gender: "Male",
    imageUrl: "https://picsum.photos/id/49/800/600",
  },
  {
    id: 50,
    matricule: "FE24A050",
    email: "person50@example.com",
    name: "Lucia Mendoza",
    gender: "Female",
    imageUrl: "https://picsum.photos/id/50/800/600",
  },
];
export type personType = (typeof demoPersons)[number];
